### ISSUE TITLE
Fix denormalized deployment issue

### ISSUE THREAD

**Issue by Kpoke** [Greenstand/treetracker-denormalization#5]

**Comment by Kpoke** [comment]
1. dev argocd seems to be down again, with the server.secretKey issue
2. After trying to redeploy, I got this error


![Image](https://github.com/Greenstand/treetracker-denormalization/assets/28721558/29abf705-4a7f-499a-bd9e-f013badf506e)

**Comment by emmanue** [comment]
Fixed.
